common:
  log_media: file
  log_level: info
  log_dir:  C:\ProgramData\CyberSec\log\
config_paths:
  config_dir:  C:\ProgramData\CyberSec\config\
  data_dir:  C:\ProgramData\CyberSec\data\
  simulation_path:   C:\ProgramData\CyberSec\config\simulation.yaml
  hub_dir:  C:\ProgramData\CyberSec\hub\
  index_path:  C:\ProgramData\CyberSec\hub\.index.json
  plugin_dir: C:\ProgramData\CyberSec\plugins\
  notification_dir:  C:\ProgramData\CyberSec\config\notifications\
crowdsec_service:
  acquisition_path:  C:\ProgramData\CyberSec\config\acquis.yaml
  parser_routines: 1
cscli:
  output: human
db_config:
  log_level: info
  type: sqlite
  db_path:  C:\ProgramData\CyberSec\data\cybersec.db
api:
  client:
    insecure_skip_verify: false
    credentials_path:  C:\ProgramData\CyberSec\config\local_api_credentials.yaml
  server:
    log_level: info
    listen_uri: 127.0.0.1:8080
    profiles_path: C:\ProgramData\CyberSec\config\profiles.yaml
    online_client:
      credentials_path:  C:\ProgramData\CyberSec\config\online_api_credentials.yaml
prometheus:
  enabled: true
  level: full
  listen_addr: 127.0.0.1
  listen_port: 6060
